<?php
// Automatically Generated by TestLink Installer - Mon, 17 Apr 23 21:33:18 +0200
define('DB_TYPE', 'postgres');
define('DB_USER', getenv('DB_USER'));
define('DB_PASS', getenv('DB_PASS'));
define('DB_HOST', getenv('DB_HOST'));
define('DB_NAME', getenv('DB_NAME'));
define('DB_TABLE_PREFIX', '');
